### ISSUE TITLE
Test: add Node.js 12 integration tests

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-plugin-lighthouse#167]
At the moment we only run unit tests on Node.js 12 (using GitHub actions), and run an integration test on Node.js 15 (using Netlify build).

We should add Node.js 12 integration tests too.

**Comment by jackbrewer** [comment]
👋  Closing this as Node 12 is EOL, and CI is running 14, 16, and 18.

We're actively adding integration tests as we add features.
