### ISSUE TITLE
Lighthouse Summary on GitHub PRs

### ISSUE THREAD

**Issue by Jud** [netlify/netlify-plugin-lighthouse#229]
**Is your feature request related to a problem? Please describe.**

We've installed the netlify-lighthouse plugin, and would like to more deeply integrate it into our GitHub PR workflow by showing lighthouse stats on newly opened PRs. The plugin runs on deploy previews, but there doesn't seem to be a simple way to get that information into the GitHub PR in an automated way.

**Describe the solution you'd like**

I would be great if there was a way to comment the lighthouse stats on the PR, or provide in rich commit stats.

**Describe alternatives you've considered**

Alternatively, we can click the build log and check the lighthouse summary. Though that's less useful at a glance.

**Additional context*

None

**Comment by erezrokah** [comment]
Hi @Jud, this sounds great to me, however it will require users to add an environment variable with a GitHub token so the plugin can access the repo.
Since it's opt-in I think that's ok.

Also if we do implement this, we should do it for all supported services (GitHub, GitLab, Bitbucket).

**Comment by charkour** [comment]
I'd like to suggest first starting with Github since that is the requested feature.

**Comment by codingChewie** [comment]
Any updates on the status of this? It's been almost two years since the issue was opened and this is a feature that would come in handy.
