### ISSUE TITLE
Compatibility with redirects/routing libraries

### ISSUE THREAD

**Issue by chetbox** [netlify/netlify-plugin-lighthouse#278]
**Is your feature request related to a problem? Please describe.**

We use `react-router` and have a `_redirects` file that looks like this:

```
/*  /index.html   200
```

**Describe the solution you'd like**

It would be great if the express server in this plugin implemented all redirects in the `_redirects` file.

**Describe alternatives you've considered**

For this use case it might be possible to serve the content with `serve --single` but we're not sure how to configure that on Netlify with this plugin.

**Additional context**

End of plugin output:

```
❯ Plugin @netlify/plugin-lighthouse ran successfully
  Summary for directory 'build': Performance: 4, Accessibility: 81, Best Practices: 67, SEO: 100, Progressive Web App: 30
  Summary for directory 'build/menu': undefined
```

**Comment by erezrokah** [comment]
Hi @chetbox, I think the way to do this is either use [Netlify CLI](https://cli.netlify.com/netlify-dev) to serve the site locally to get redirects support, or audit the live site instead of a local version as mentioned in https://github.com/netlify-labs/netlify-plugin-lighthouse/issues/152#issuecomment-824176171

**Comment by chetbox** [comment]
Thanks for the quick response!

The preview URL doesn't get deployed if our Lighthouse checks fail, and possibly isn't published at the point this runs anyway?

Can the Netlfiy CLI (or any command) while the plugin is running? I haven't seen an obvious way to do that.

**Comment by erezrokah** [comment]
> The preview URL doesn't get deployed if our Lighthouse checks fail, and possibly isn't published at the point this runs anyway?

The suggested change in the linked comment is ti run the check after the site preview is deployed.

> Can the Netlfiy CLI (or any command) while the plugin is running? I haven't seen an obvious way to do that.

The plugin can start the CLI and close it when the audit is finished

**Comment by chetbox** [comment]
> The plugin can start the CLI and close it when the audit is finished

Thanks! This seems like the right solution for us. How do we configure this? I don't see any documentation in the README for how one might run the CLI or arbitrary commands before/after the plugin runs.

**Comment by erezrokah** [comment]
> Thanks! This seems like the right solution for us. How do we configure this? I don't see any documentation in the README for how one might run the CLI or arbitrary commands before/after the plugin runs.

This is not implement yet. I suggested it as a way to resolve this feature request.

Sorry for the confusion

**Comment by aitchiss** [comment]
Hi @chetbox  👋 

I wanted to reach out to see if you'd be interested in helping us test some experimental functionality that should unblock the issues you're seeing with redirects?

This isn't ready for a full release yet, but if you'd like to help us test it out, all you need to do is:

- Upgrade to v4.1.0 of the plugin
- Enable the experimental functionality by either [creating an environment variable](https://docs.netlify.com/environment-variables/overview/) `LIGHTHOUSE_RUN_ON_SUCCESS='true'`, or adding the below input to your netlify.toml:

```
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    run_on_success = "true"
```

Once you've done this, the plugin will now run _after_ your deploy is completed, and will run against the **live deploy URL** taking into account your redirects.

As I mention, this is still experimental at this time, but we'd happy to hear any feedback from some early testing!

**Comment by chetbox** [comment]
Hi @aitchiss. Sorry, but I'm no longer working on this project.

**Comment by aitchiss** [comment]
Closing this issue as version 5.0.0 of the plugin runs against the live deploy URL by default, therefore ensuring compatibility with redirects and routing libraries.

**Comment by nlm-pro** [comment]
> @aitchiss Closing this issue as version 5.0.0 of the plugin runs against the live deploy URL by default, therefore ensuring compatibility with redirects and routing libraries.

I'm using v5.0.0 but I can't manage to test routes, even though everything works correctly once deployed. I only use one index.html file, with a custom-made minimalistic router, and configured redirections properly via a _redirects file `/*  /index.html  200`. There are only two routes: "/cv" and a default one ("/").

Here is the associated netlify.toml :

```toml
[build]
command = "npm run build"
base = "/"
publish = "build"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs]
fail_deploy_on_score_thresholds = "true"

[[plugins.inputs.audits]]
path = "/"

[plugins.inputs.thresholds]
performance = 1
accessibility = 1
best-practices = 1
seo = 0.9

[[plugins.inputs.audits]]
path = "/cv"

[plugins.inputs.audits.thresholds]
performance = 1
accessibility = 1
best-practices = 1
seo = 0.9
```

I tested with pretty much all variations (paths with or without the slash, disabling `fail_deploy_on_score_thresholds`, etc.) but I always get a 404 error :

```
ERRORED_DOCUMENT_REQUEST
Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404)
```

Here is the associated PR for reproduction: https://github.com/nlm-pro/noelmace.com/pull/38

**Comment by aitchiss** [comment]
Hi @nlm-pro! I visited your linked PR and the [associated deploy log](https://app.netlify.com/sites/noelmace-page/deploys/64dd24d0a854c600089c0e7a), and I can see the lighthouse score reports in your deploy page:

![](https://github.com/netlify/netlify-plugin-lighthouse/assets/20773163/3189abaa-0c20-4d72-8d3a-f8a0a6f5245d)

I can see however that the path being audited isn't quite right - e.g. it is auditing `//` and `//cv`. So I would recommend setting the paths to "" and "cv" respectively

**Comment by aitchiss** [comment]
> Seems like fail_deploy_on_score_thresholds isn't compatible with redirects/routing libraries.

Yes, that's correct. To be able to fail a deploy if thresholds aren't met, the plugin needs to run _before_ the deploy is live. At the moment this is achieved by statically serving up your build folder contents on an express server (so we audit `localhost` instead of the live deploy). One of the key limitations with this is that redirects/routing libraries aren't taken into account.

> Yet, I'd like to see the job actually fail when score thresholds aren't met in order to see it in the PR Github

💯 Totally understand. This might be added at some point in the future, but unfortunately is a bigger lift. In future, we'd also like to post the lighthouse score diff to the GitHub PR which, short of failing the deploy, might also help achieve what you're looking for.
