### ISSUE TITLE
Allow configuring the device to monitor (Desktop / Mobile)

### ISSUE THREAD

**Issue by javiercardenaswork** [netlify/netlify-plugin-lighthouse#387]
I did not see in the docs a way to configure the device, only by category (performance, SEO, etc). 

![image](https://user-images.githubusercontent.com/87084313/157554027-7b0ca98d-9700-46b6-b71b-956e49dcbad2.png)

I think that by default is mobile, but right now, I just want to monitor only in Desktop. Is this possible?

![image](https://user-images.githubusercontent.com/87084313/157553336-a0bf4ce5-d94d-4961-ae72-0cea750157da.png)

**Comment by jackbrewer** [comment]
Hey @javiercardenaswork! It's been a while, but this is now available when using `v3.5.0` of this plugin.

Mobile is still the default, but you can opt-in to desktop testing instead using the following `netlify.toml` addition.

```
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.settings]
    preset = "desktop"
```

**Comment by UmungoBungo** [comment]
sorry to re-surface an older thread but I couldn't think of a better way to ask this question. Is there a way to use desktop for some paths, and mobile for others?

**Comment by jackbrewer** [comment]
Hey, it's not currently possible I'm afraid, but I can add it to our roadmap to take a look at in future.

If you don't mind sharing, is there a specific reason to use different devices per-path? Would you be testing the same path against both devices? Or do you have some pages which need to specifically choose one over the other maybe?

**Comment by UmungoBungo** [comment]
It would be much appreciated if you could add it to the roadmap 🙏

At this stage in development I only need desktop and mobile for some pages, and just desktop for others. But long term, I would want to test both, and if that functionality existed now, I don't see an issue with testing both and ignoring the results I don't need as well.
