### ISSUE TITLE
Big deviation on performance metric

### ISSUE THREAD

**Issue by javiercardenaswork** [netlify/netlify-plugin-lighthouse#388]
**Describe the bug**
Big deviation on performance metric using the netlify plugin.

**To Reproduce**

I set multiple tests on my Netlify deploy to see how the tool worked. This is what I got.

![image](https://user-images.githubusercontent.com/87084313/157881931-478537f2-9cf9-49ba-a205-59079851f364.png)

I was testing with multiple thresholds, because I was trying to pass the test. And as you can see the deviation is quite big ~10%.

**Expected behavior**
I was expecting some deviation between results, but not that big. I would expect like ~3 similar from what I get on the Browser Dev Tools.

**Screenshots**
![image](https://user-images.githubusercontent.com/87084313/157880907-b0a4857d-ab49-49a1-a8c7-9e23d8c659d7.png)

![image](https://user-images.githubusercontent.com/87084313/157880969-84eb5059-96ef-4069-83f1-719b7e761956.png)

![image](https://user-images.githubusercontent.com/87084313/157881008-d4150143-52a4-4e1c-8315-fcf8a64c7cc6.png)

![image](https://user-images.githubusercontent.com/87084313/157881076-760e04df-28c9-4ac4-8cc4-cda481263425.png)

![image](https://user-images.githubusercontent.com/87084313/157881112-4a4e7fb3-b72b-4aab-bd5b-ebff961a0792.png)

**Desktop (please complete the following information):**
    - OS: Linux
    - Browser: Chrome
    - Version: 99.0.4844.51 (Official Build) (64-bit)

**Comment by jackbrewer** [comment]
Hey @javiercardenaswork, Sorry for the lack of follow-ups to your issue report.

Version 4 of this plugin adds the ability to view full Lighthouse reports in the Netlify UI ([read more in the docs](https://docs.netlify.com/monitor-sites/lighthouse/)).

This allows for a much more detailed review of a single run and may help track down which metrics are causing your variations between deploys. The settings used for each run can be found in the footer of the Lighthouse report, which can also help debug against the settings used in the Browser dev tools.

I'm going to close this issue for now, but please reach out if you spot anything we can help with.
