### ISSUE TITLE
SEO score is lower (92) than what other Lighthouse tools report (100)

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [netlify/netlify-plugin-lighthouse#397]
Thanks so much for this plugin! I've been wanting something like this for a while now.

**Describe the bug**

Running Lighthouse on https://www.fluid-type-scale.com/ reports 100 in SEO. With the build plugin, the SEO score drops to 92, suggesting that one or more audits failed. I wasn't able to figure out how to view the detailed report in my deploy log.

**To Reproduce**
1. View the public deploy log here and confirm that the site scores 92 in SEO: https://app.netlify.com/sites/zen-ptolemy-a47e6d/deploys/62431c6ce013151b523f4d61
2. Run Lighthouse in your dev tools or via https://web.dev/measure/ on https://www.fluid-type-scale.com/, and observe that it scores 100 for SEO.

**Expected behavior**
The build plugin SEO score should not deviate greatly from those provided by other Lighthouse-powered tools.

**Plugin version**: 2.1.3

**Comment by jackbrewer** [comment]
Hey @AleksandrHovhannisyan, Sorry for the lack of follow-ups to your issue report.

Version 4 of this plugin adds the ability to view full Lighthouse reports in the Netlify UI ([read more in the docs](https://docs.netlify.com/monitor-sites/lighthouse/)).

This allows for a much more detailed review of a single run and may help track down which audits are causing your SEO score to drop when running on Netlify.

I'm going to close this issue for now, but please reach out if you spot anything we can help with.
