### ISSUE TITLE
Plugin update notification in build summary

### ISSUE THREAD

**Issue by MetalMatt-Netlify** [netlify/netlify-plugin-lighthouse#398]
**Describe the bug**
The Lighthouse output in the build summary states that there is an update available for the plugin, but the latest available version is already installed.

**To Reproduce**
1. Install the Lighthouse Build Plugin on a Site from the Netlify Plugin Directory
2. Run a build on the site
3. Wait for build to complete.
4. Notice the plugin version in the build logs is 2.1.3
5. Expand the `1 plugin ran successfully` row under the Deploy Summary
6. Notice the `Update available` indicator 

**Expected behavior**
As we have the latest version of the plugin available, I would expect this `Update available` message to not be present.

You can further confirm this by following the link on `Update available` and seeing that the latest version is 2.1.3.

**Screenshots**

![image](https://user-images.githubusercontent.com/79875905/161087852-e877a4f1-1673-4629-afc0-6a9feba2ca6b.png)
![image](https://user-images.githubusercontent.com/79875905/161087891-707d9207-b3fd-4bc9-94a2-0470a1396247.png)
![image](https://user-images.githubusercontent.com/79875905/161087910-bfa9cd58-155e-4fa9-8ae1-d9718f001a05.png)

**Desktop (please complete the following information):**
    - OS: macOS 12.1
    - Browser Chrome Version 99.0.4844.84 (Official Build) (arm64)

**Comment by jackbrewer** [comment]
Closing as complete. This was addressed at an App level and was not specific to this plugin 👍
