### ISSUE TITLE
Auditing Statically Generated Next.js Pages

### ISSUE THREAD

**Issue by dananthony** [netlify/netlify-plugin-lighthouse#402]
**Describe the bug**
We are having trouble configuring the plugin to audit statically generated pages in a Next.js site. We are using Next's internationalised routing, so the page we'd like to audit is available at `/en-US/products/product-name`.

We've tried passing this route to `[[plugins.inputs.audits]]` and also the path to the generated page in the build output, but both result in the following error: `Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404)`.

What is the correct way to go about auditing a statically generated page like this?

**To Reproduce**
1. Install the plugin on a Next.js site using i18n routing
2. Configure `netlify.toml` to audit a statically generated page:
```
[[plugins.inputs.audits]]
    path = "/en-US/products/product-name"
```
3. Observe the error in the build output: `Lighthouse was unable to reliably load the page you requested...`

**Expected behavior**
The plugin audits the page specified in `[[plugins.inputs.audits]]`

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by jackbrewer** [comment]
Hey @dananthony, Sorry for the lack of follow-ups to your issue report.

Version 4 of this plugin changes how paths are interpreted when running the Lighthouse tests, reducing chances of 404s, and hopefully addressing your issue. Under the hood, the plugin runs agains static HTML files in your build/output folder so as you mentioned, using the path to the generated page would be a good place to start.

I'm going to close this issue for now, but please get in touch if we can help with anything else.
