### ISSUE TITLE
Customer issue: Results not reported after plugin seems to run successfully

### ISSUE THREAD

**Issue by fool** [netlify/netlify-plugin-lighthouse#415]
**Describe the bug**
Plugin v 2.1.3 claims to run successfully, but reports no `Results` for a single site

**To Reproduce**
While I cannot share the customer's codebase so I don't have repro steps, I can share some logs.  Their plugin output is verbose - but that seems to be the way of the plugin in general.  I can work with any dev who might pick this up 1:1 to give more info, or perhaps the customer whom I will share this report with will be willing to share more details publicly.

**Expected behavior**
After the plugin says "Generating results" and before it says "Killing Chrome instance", we'd expect the see a `Results` stanza.  But in this case, we don't:

```
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:status Auditing: Tap targets are sized appropriately
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:Runner:warn MetaElements gatherer, required by audit tap-targets, did not run.
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:status Auditing: Document has a valid `hreflang`
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:Runner:warn LinkElements gatherer, required by audit hreflang, did not run.
9:48:47 AM: Post processing - redirect rules
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:status Auditing: Document avoids plugins
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:Runner:warn EmbeddedContent gatherer, required by audit plugins, did not run.
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:status Auditing: Document has a valid `rel=canonical`
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:Runner:warn LinkElements gatherer, required by audit canonical, did not run.
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:status Auditing: Structured data is valid
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:status Generating results...
9:48:47 AM: Post processing done
9:48:27 AM: Tue, 07 Jun 2022 16:48:27 GMT LH:ChromeLauncher Killing Chrome instance 1760
9:48:27 AM: ​
9:48:27 AM: (@netlify/plugin-lighthouse onPostBuild completed in 4.8s)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/229024/172512749-79a6cc9e-b1ed-4e85-8718-7a8f5d8a63e2.png)

**Desktop (please complete the following information):**
    - I think this is irrelevant to this report :)

**Smartphone (please complete the following information):**
    - I think this is irrelevant to this report :)

**Additional context**
Customer is a new user of the plugin so not sure what it should look like;  I as a Netlify employee have seen other plugin runs that do include a "results" stanza right in that spot in the logs.

Is there anything else the customer (or Netlify) can try, to debug this situation?

**Comment by bhavana-netlify** [comment]
From the summary up top after every deploy, I see this in this particular build

>
@netlify/plugin-lighthouse ran successfully
Summary for directory 'public': undefined


I am running the plugin on a demo site myself and it runs as expected with v1 and v2 of the plugin. 
https://app.netlify.com/sites/product-demo/deploys

**Comment by NetlifyMatt** [comment]
Thanks for this report. We'll have a look and report back with any findings.

**Comment by charkour** [comment]
Can confirm my team is facing the same issue. 

Note that we installed the plugin with the direct in-app installation link and **not** through `netlify.toml`

<img width="755" alt="image" src="https://user-images.githubusercontent.com/33156025/173834399-d65dc244-0892-4f6a-9ff0-3e0e345f4edc.png">

**Comment by charkour** [comment]
Also, in the deploy logs, it says `.next undefined`. Not sure if that is an issue but it seems it could be. 

<img width="423" alt="image" src="https://user-images.githubusercontent.com/33156025/173850797-776da0bd-6465-422b-9187-334cd669cb1f.png">

**Comment by roomman** [comment]
Same issue here. Let me know if I can provide you with any info to assist. 👍🏻

**Comment by MetalMatt-Netlify** [comment]
Hello all, we believe this issue has been resolved with the latest version of the plugin. If possible, can you please upgrade to the latest version of the plugin and verify if this issue has been addressed? If not, please let us know. Thank you!
