### ISSUE TITLE
Lighthouse plugin occasionally fails with "Build exceeded maximum allowed runtime"

### ISSUE THREAD

**Issue by passion4code** [netlify/netlify-plugin-lighthouse#421]
**Describe the bug**
Lighthouse plugin fails the Netlify build with an error of "Build exceeded maximum allowed runtime".

**To Reproduce**
1. Activate the plugin
2. Run a build
3. See the error (only happens sometimes)

**Expected behavior**
The Lighthouse plugin should have sane timeouts in place (or maybe it is an error getting swallowed and there needs to be improvements to exception handling) and should not block the build from succeeding due to maximum allowed runtime. 

**Screenshots**
![Screen Shot 2022-06-28 at 5 00 31 PM](https://user-images.githubusercontent.com/703935/176323922-d4084a01-7acb-4a03-8b51-83f7ca12ad4d.png)

**Desktop (please complete the following information):**
    - N/A as this has to do with the lighthouse plugin during the build process. Ubuntu v20 is the build image being used. 

**Smartphone (please complete the following information):**
        - N/A as this has to do with the lighthouse plugin during the build process. Ubuntu v20 is the build image being used. 

**Additional context**

In my case, there is a "navigating to about:blank' step in which this freezes at. In a successful run, the next step after this is to disconnect the browser which takes about 1 minute in usual runs. 

![Screen Shot 2022-06-28 at 5 11 07 PM](https://user-images.githubusercontent.com/703935/176324716-c42b6a24-c2be-4993-924d-d2cd070bf85c.png)

**Comment by MetalMatt-Netlify** [comment]
One of the sites with the issue: https://app.netlify.com/sites/riotgames-publishing-wildrift-c35f28/overview (`e71b8244-1a08-4f31-8b03-f19a87ee16e3`).

**Comment by MetalMatt-Netlify** [comment]
Follow up: customer mentioned that they upgraded to the latest version of the plugin and hadn't seen any issues since. Will follow up with the customer again today to verify.

**Comment by MetalMatt-Netlify** [comment]
Closing this issue as the issue appears to have subsided since upgrading to the latest version of the plugin. Please let us know if the issue returns. Thank you! 🙌
