### ISSUE TITLE
upgrading to version 3.1 issue

### ISSUE THREAD

**Issue by alfred-tuinman** [netlify/netlify-plugin-lighthouse#460]
I tried to upgrade from v3.0 to 3.1  (actually the latest but this is the version upgrade causing the error)

> Plugin "@netlify/plugin-lighthouse" failed                    
> ────────────────────────────────────────────────────────────────
> 
>   Error message
>   Error: Failed with error:
> 
>   utils.status.show() must only contain "title", "summary" or "text" properties, not "extraData"
> 
>   Plugin details
>   Package:        @netlify/plugin-lighthouse
>   Version:        3.1.0
>   Repository:     git+https://github.com/netlify/netlify-plugin-lighthouse.git
>   npm link:       https://www.npmjs.com/package/@netlify/plugin-lighthouse
>   Report issues:  https://github.com/netlify/netlify-plugin-lighthouse/issues
> 
>   Error location
>   In "onPostBuild" event in "@netlify/plugin-lighthouse" from netlify.toml and package.json
>       at onPostBuild (/node_modules/@netlify/plugin-lighthouse/src/index.js:293:7)

I use Ubuntu 22.04 and ran the "netlify build" command on my local terminal

**Comment by kevinsamoei** [comment]
Hi @alfred-tuinman , Do you have a specific netlify build image version set for that site?

**Comment by alfred-tuinman** [comment]
No i just wanted to upgrade a version. Nothing special to my knowledge.

**Comment by kevinsamoei** [comment]
If you could share the site name or site ID that would help with the investigation. The reason I think maybe the site's build image is old is that the error you are seeing was fixed in a newer version of the build image.

**Comment by alfred-tuinman** [comment]
Will look at it but our internet is down. Rather, my 80m fibre optic cable
is playing up so I am waiting for a chap with a machine to test the cable
and or fix the connectors. No idea why it's playing up as it is normally
not touched.

Cheers from my mobile device.
Alfred

**Comment by aitchiss** [comment]
Hi @alfred-tuinman - please can you try upgrading to the latest version of the plugin (v4) and let us know if you're still encountering this issue? In the meantime, I'm going to close this but feel free to re-open if you're still having problems!
