### ISSUE TITLE
Surface error message if requested path/url 404s

### ISSUE THREAD

**Issue by jackbrewer** [netlify/netlify-plugin-lighthouse#494]
If the path/url to be tested can not be found, the Lighthouse test appears to complete with no scores output.

Lighthouse does mention the target page was not found but it's buried halfway through the verbose output – between the "gather" and "audit" phases.

```
LH:GatherRunner:error Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404)
```

The Deploy Summary claims:
> **@netlify/plugin-lighthouse ran successfully**
> Summary for path 'build/': undefined

**Describe the solution you'd like**
This error should be made more obvious. We could:
- Add a message to the _end_ of the plugins log content, where the scores would usually appear
- Amend the summary to replace the `undefined` with a message such as `Summary for path 'build/': the path could not be loaded (404)`
- Error the plugin run as failed if all the reports being run return 404? It is possible to have successful and 404ing reports in the same run, so we'd need to consider this in more detail.

**Comment by nasivuela** [comment]
How would UI retrieve that info? From the logs or the API?

**Comment by jackbrewer** [comment]
We can access the `runtimeError` field of the Lighthouse output and use it it to add content to the summary before logging.

**Comment by jackbrewer** [comment]
This will work for multiple audit runs, where only one may have failed, e.g.

```
Summary for path `/`: Performance 91, Best Practices… etc
Summary for path `/contact`: the path could not be loaded (404)
```
