### ISSUE TITLE
surface runtime errors

### ISSUE THREAD

**Issue by kevinsamoei** [netlify/netlify-plugin-lighthouse#503]
Sometimes when there is a runtime error, we will show results as `undefined`. It would be neat if we actually surface those errors.
We can currently view these errors through the report in the UI but would be helpful to also surface those in the deploy summary/build logs. 

Here is an example of a report with a `NO_LCP` runtime error - https://gist.github.com/kevinsamoei/81d719fdfc91c77f2e0684395cb467b1

Notice we have `runtimeError` and `runWarnings` fields. we should leverage those and show those error messages if the summary is not there

<img width="574" alt="Screen Shot 2022-10-24 at 20 31 05" src="https://user-images.githubusercontent.com/15800486/197589174-fad75d71-051d-4831-868f-1eb2f6d43d12.png">

**Comment by jackbrewer** [comment]
Related to #494

**Comment by jackbrewer** [comment]
@nasivuela @aitchiss  This is a good candidate for prioritizing (along with #494 which is the same thing, just more focussed on 404s)
