### ISSUE TITLE
Deprecated dependency breaks plugin installation

### ISSUE THREAD

**Issue by lime** [netlify/netlify-plugin-lighthouse#543]
One of my sites on Netlify is failing to build, and it seems like the culprit is one of the dependencies of this plugin being deprecated. I saw that someone on the Netlify support forums [reported the same issue](https://answers.netlify.com/t/builds-failing-due-to-intl-messageformat-parser-1-8-1-deprecation/83951), and I thought I'd give the maintainers of this plugin a heads up, with the limited information I have. :)

The package in question is [intl-messageformat-parser](https://www.npmjs.com/package/intl-messageformat-parser), and it seems to be part of the postinstall step to Puppeteer. I see that #540 was merged yesterday, which might be related.

Another data point is that my last successful build used `@netlify/plugin-lighthouse@4.0.5`, and all the failed ones use `@netlify/plugin-lighthouse@4.0.6`.

Here's the relevant excerpt from the logs:

```
11:40:21 AM:   Netlify Build                                                 
11:40:21 AM: ────────────────────────────────────────────────────────────────
11:40:21 AM: ​
11:40:21 AM: ❯ Version
11:40:21 AM:   @netlify/build 29.5.1
[...]
11:40:21 AM: ❯ Installing plugins
11:40:21 AM:    - @netlify/plugin-lighthouse@4.0.6
11:40:30 AM: ​
11:40:30 AM:   Dependencies installation error                               
11:40:30 AM: ────────────────────────────────────────────────────────────────
11:40:30 AM: ​
11:40:30 AM:   Error message
11:40:30 AM:   Error while installing dependencies in /opt/build/repo/.netlify/plugins/
11:40:30 AM:   npm WARN deprecated intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
11:40:30 AM: ​
11:40:30 AM:   > puppeteer@19.6.0 postinstall /opt/build/repo/.netlify/plugins/node_modules/puppeteer
11:40:30 AM:   > node install.js
11:40:30 AM: ​
11:40:30 AM:   module.js:550
11:40:30 AM:       throw err;
11:40:30 AM:       ^
```

The site is running on the Ubuntu Focal 20.04 build image. It's an old Jekyll site, with no particular Node / NPM version specified, so I assume it just uses the default on that image.

I haven't been able to debug it much further, since this is on a free plan, and the Lighthouse integration seems to be paywalled nowadays. I may have opted in to this plugin through the UI sometime before, and now I see no way of toggling it off. The `netlify.toml` of this site does not contain any plugins.

Hope this information is of some use.

**Comment by jackbrewer** [comment]
I've just released `@netlify/plugin-lighthouse@4.0.7` which reverts puppeteer back to the version we were using in `4.0.5`. Hopefully everything should be back to normal!

Thanks again for the issue report – it's not something we encountered during our testing so it will be interesting for us to try and replicate!

I'm going to close this issue, but please re-open it if you still have issues with the latest release ☺️

**Comment by lime** [comment]
I thought I'd leave a comment that the 4.0.7 release indeed allowed deploys to go through again, thank you! Thanks also for the pointer to the integrations list, I was able to toggle it from there.

Let me know if you'd benefit from getting a scrubbed version of my repo, or want to look more closely at the Netlify app and deployments in question, in case reproducing it turns out to be difficult.

**Comment by jackbrewer** [comment]
Thanks @lime, that's a very kind offer ☺️. We've already spotted the root issue thanks to the logs snippet you provided (and the report in the forums. We're working on a fix in the background. We've also been able to add a few testing scenarios to our release plan to avoid something like this happening again. 🎉
