### ISSUE TITLE
Ability to Run Audit on HTTPS Protocol

### ISSUE THREAD

**Issue by dsolanorush** [netlify/netlify-plugin-lighthouse#546]
**Is your feature request related to a problem? Please describe.**
This plugin appears to lack a setting to run audit against `https` protocol. This impacts our Best Practices score, and possibly other metrics of the audit.

**Describe the solution you'd like**
We have multiple sites running on a common codebase, so a setting to force `https` (or simply to have https be the default) would be great.

**Describe alternatives you've considered**
I did not see anything in the docs aside from an absolute URL option that would resolve this issue. Again, we serve multiple sites with a shared `netlify.toml` file, so I'm not sure an absolute URL of something like `https://localhost` would work, but I will try it.

**Additional context**
My suggestion would be to have the audit run on https by default. Suggested change in `/src/lib/get-server/index.js`:

Current
```
const server = {
    listen: (func) => {
      console.log(
        `Serving and scanning site from directory ${chalk.magenta(serveDir)}`,
      );
      return app.listen(port, host, func);
    },
    close: (instance) => instance.close(),
    url: `http://${host}:${port}`,
  };
```

Default HTTPS
```
const server = {
    listen: (func) => {
      console.log(
        `Serving and scanning site from directory ${chalk.magenta(serveDir)}`,
      );
      return app.listen(port, host, func);
    },
    close: (instance) => instance.close(),
    url: `https://${host}:${port}`,
  };
```

**Comment by aitchiss** [comment]
Thanks for filing this issue!

Unfortunately changing this text to `https` results in an error `ERR_SSL_PROTOCOL_ERROR` because the minimal server we are using is not "speaking" https when it serves up localhost. The goal to verify the lighthouse scores in an environment closer to production is however something we're currently working on, just in a slightly different way!

In future, you'll be able to choose to run your lighthouse audit on the actual live deploy URL (rather than the content served up internally on `localhost`). Do you think that would fulfil your use-case? If so, we hope to have a beta version available soon.

**Comment by dsolanorush** [comment]
@aitchiss Thank you for the reply. Yes, I believe that would fulfill our use case. I would definitely be interested in the upcoming beta release!

**Comment by aitchiss** [comment]
Awesome! Let me close this issue for now, but I've linked it on our internal beta issue to remind us to give you a heads up when it's ready for early testing!

**Comment by aitchiss** [comment]
Hi @dsolanorush 👋  I'm happy to share that version `4.1.0` of the plugin allows you to enable an experimental version of the functionality I mentioned! This isn't ready for a full release yet, but if you'd like to help us test it out, all you need to do is:

- Upgrade to `v4.1.0` of the plugin
- Enable the experimental functionality by **either** [creating an environment variable](https://docs.netlify.com/environment-variables/overview/) `LIGHTHOUSE_RUN_ON_SUCCESS='true'`, or adding the below input to your `netlify.toml`:

```
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    run_on_success = "true"
```

Once you've done this, the plugin will now run _after_ your deploy is completed, and will run against the live deploy URL.

As I mention, this is still experimental at this time, but we'd happy to hear any feedback from some early testing!

**Comment by dsolanorush** [comment]
Fantastic! I'm looking forward to trying this out. Thank you!

Cheers,

<https://www.rushmarket.com/>
*Drey Solano*
STAFF Software Engineer
technology
WWW.RUSHMARKET.COM <https://www.rushmarket.com/>
<https://www.facebook.com/therushmarketomaha>
<https://instagram.com/therushmarketomaha>

**Comment by dsolanorush** [comment]
@aitchiss - Just wanted to wanted to report that the plugin is now successfully running against live deploy URLs. Thanks again for getting this feature added so quickly 🙏

**Comment by aitchiss** [comment]
That's great news - thank you for confirming @dsolanorush! In the near future we'll be shipping a major version where we flip the "on success" behaviour to be the default, at which point you'll no longer need the extra settings I mentioned above, but I'm glad to hear you're unblocked for now!
