### ISSUE TITLE
Lighthouse unable to load a NextJs site

### ISSUE THREAD

**Issue by benjamin-fleet** [netlify/netlify-plugin-lighthouse#566]
Hello,

I am using this plugin on Netlify with `@netlify/plugin-nextjs`. When I try to build the site with the Lighthouse plugin I get the following messages :
```
Serving and scanning site from directory out
...
LH:GatherRunner:error Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404) http://localhost:5100/
```

Maybe it is linked to our directory structure ?

In the Netlify UI :
Base directory : `www`

Our netlify.toml file includes this :
```
[build]
  publish = "out"
```

In the build logs :
```
2:29:49 PM: 🌍️ Copying public folder to /opt/build/repo/www/out
2:29:50 PM: 💼 Copying static NextJS assets to /opt/build/repo/www/out
```

It seems `netlify-plugin-lighthouse` is using the PUBLISH_DIR which seems to be correctly mapped to `/out`, but I don't know how I can check that. Maybe the `www` prefix is missing somewhere ?

Any ideas ?

Thank you in advance for your help.

**Comment by benjamin-fleet** [comment]
Closing the ticket, seems like it's linked to this issue :
https://github.com/netlify/netlify-plugin-lighthouse/issues/405

**Comment by aitchiss** [comment]
Hi @benjamin-fleet  👋 

I wanted to reach out to see if you'd be interested in helping us test an experimental version of the functionality @jackbrewer mentioned above, as it should unblock the issues you're facing?

This isn't ready for a full release yet, but if you'd like to help us test it out, all you need to do is:

- Upgrade to v4.1.0 of the plugin
- Enable the experimental functionality by either [creating an environment variable](https://docs.netlify.com/environment-variables/overview/) `LIGHTHOUSE_RUN_ON_SUCCESS='true'`, or adding the below input to your netlify.toml:

```
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    run_on_success = "true"
```

Once you've done this, the plugin will now run _after_ your deploy is completed, and will run against the live deploy URL.

As I mention, this is still experimental at this time, but we'd happy to hear any feedback from some early testing!

**Comment by jlevy-io** [comment]
> Hi @benjamin-fleet 👋
> 
> I wanted to reach out to see if you'd be interested in helping us test an experimental version of the functionality mentioned in the issue you linked, as it should unblock the issues you're facing?
> 
> This isn't ready for a full release yet, but if you'd like to help us test it out, all you need to do is:
> 
> * Upgrade to v4.1.0 of the plugin
> * Enable the experimental functionality by either [creating an environment variable](https://docs.netlify.com/environment-variables/overview/) `LIGHTHOUSE_RUN_ON_SUCCESS='true'`, or adding the below input to your netlify.toml:
> 
> ```
> [[plugins]]
>   package = "@netlify/plugin-lighthouse"
> 
>   [plugins.inputs]
>     run_on_success = "true"
> ```
> 
> Once you've done this, the plugin will now run _after_ your deploy is completed, and will run against the live deploy URL.
> 
> As I mention, this is still experimental at this time, but we'd happy to hear any feedback from some early testing!

@aitchiss just wanted to say this is working great for me on my Next 13 site.   Found this thread on Google trying to figure out why my plugin had stopped working.   Much appreciated

**Comment by aitchiss** [comment]
Thank you for the feedback @jlevy-io - really pleased to hear it!

**Comment by christopher-theagen** [comment]
@aitchiss Hi Suzanne- might https://github.com/netlify/netlify-plugin-lighthouse/issues/598 be related to this issue?
