### ISSUE TITLE
Broken builds due to netlify/plugin-lighthouse internal error.

### ISSUE THREAD

**Issue by hardyjohnson** [netlify/netlify-plugin-lighthouse#578]
**Describe the bug**
Broken builds with the following error:

Plugin "@netlify/plugin-lighthouse" internal error

Could not import plugin:
Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/build/repo/src/.netlify/plugins/node_modules/lighthouse-logger/index.js from /opt/build/repo/src/.netlify/plugins/node_modules/lighthouse/lighthouse-core/gather/fetcher.js not supported.
Instead change the require of index.js in /opt/build/repo/src/.netlify/plugins/node_modules/lighthouse/lighthouse-core/gather/fetcher.js to a dynamic import() which is available in all CommonJS modules.

While loading "@netlify/plugin-lighthouse" from Netlify app at Object.<anonymous> (/opt/build/repo/src/.netlify/plugins/node_modules/lighthouse/lighthouse-core/gather/fetcher.js:18:13) at Object.<anonymous> (/opt/build/repo/src/.netlify/plugins/node_modules/lighthouse/lighthouse-core/gather/driver.js:8:17) at Object.<anonymous> (/opt/build/repo/src/.netlify/plugins/node_modules/lighthouse/lighthouse-core/runner.js:9:16) at Object.<anonymous> (/opt/build/repo/src/.netlify/plugins/node_modules/lighthouse/lighthouse-core/index.js:8:16) at async Promise.all (index 0) at async importLogic (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/child/logic.js:25:29) at async getLogic (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/child/logic.js:10:19) at async Object.load (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/child/load.js:12:19) at async handleEvent (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/child/main.js:28:42) at async process.<anonymous> (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/ipc.js:91:24)

Error properties: { code: 'ERR_REQUIRE_ESM' }

**To Reproduce**
1. Deploy Netlify site
2. Build error occurs
3. Deploy fails

**Expected behavior**

A working deploy and lighthouse scoring of the build.

This may be related to a release by the Chrome team of lighthouse-logger: https://github.com/GoogleChrome/lighthouse/issues/15085

https://www.npmjs.com/package/lighthouse-logger

**Comment by jackbrewer** [comment]
Thanks for the detailed report and for jumping into the Lighthouse issues too! I've done some testing this morning and all seems ok again. Along with [your comment](https://github.com/GoogleChrome/lighthouse/issues/15085#issuecomment-1550542843), I think we can close this ☺️
