### ISSUE TITLE
Add `onSuccess` feature documentation

### ISSUE THREAD

**Issue by AndreyYevtukhov** [netlify/netlify-plugin-lighthouse#586]
I've spent 3 hours reading your release notes, checking PRs and source code to find out that it is possible to:

- run Lighthouse checks on the actual deployed site (and not on the intermediate server during the build step)
- run Lighthouse checks against real pages of SPA
- not block our build (increasing build time)

---

It is as simple as setting `LIGHTHOUSE_RUN_ON_SUCCESS=TRUE` in [ENV variables](https://docs.netlify.com/environment-variables/overview/) and running Lighthouse against different URLs:

```
# netlify.toml

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = ""
  
  [[plugins.inputs.audits]]
    path = "contact"
  
  [[plugins.inputs.audits]]
    path = "blog/post/123"
```  

So please, guys, add some docs on it :) 
The feature is cool and valuable, but maybe there is something else I'm missing that can be shared!

Thanks for your work @jackbrewer and @aitchiss!

---

For those who are interested in where I found it and how it works:

- https://github.com/netlify/netlify-plugin-lighthouse/pull/558 - `onSuccess` feature is introduced
- https://github.com/netlify/netlify-plugin-lighthouse/pull/570 - env variable name is changed

**Comment by aitchiss** [comment]
@AndreyYevtukhov thank you for your message! This functionality is still in its experimental phase, but in the near future we plan to release it fully as the default behaviour, along with documentation 🙂

**Comment by aitchiss** [comment]
Closing this issue as v5.0.0 of the plugin has now shipped. This release changes plugin behaviour to run `onSuccess` (against the live deploy URL) by default, and updates the README accordingly. @AndreyYevtukhov thanks again for raising this, and please note that you are now able to remove the environment variable `LIGHTHOUSE_RUN_ON_SUCCESS`.
